### ISSUE TITLE
Instructions/Docs

### ISSUE THREAD

**Issue by AngelMunoz** [GracesGames/2DTileMapLevelEditor#12]
Hello! This project looks quite interesting and I'd love to use it, however I didn't find any instructions or docs
about how to use it, where should I store assets for it to pick them up etc.

Thank you for oss'ing a tool like this!

**Comment by GracesGames** [comment]
Hi,

Thank you for showing interest in the project. That is always nice to hear.
I'm currently working on a documentation website, similar to the one for my [Simple File Browser](https://gracesgames.github.io/SimpleFileBrowser/).
This will, as a start, contain the same information as the [wiki](https://github.com/GracesGames/2DTileMapLevelEditor/wiki), but can be easily extended with better setup examples (e.g. GIFs)

Hope that this information can get you started for now, else please have a bit more patients ;)

P.S. I'm also working on version 1.3 which will be released soon.

**Comment by AngelMunoz** [comment]
Thank you so much! I don't know why didn't I check the wiki sorry!
