### ISSUE TITLE
how to make the grid wider ?

### ISSUE THREAD

**Issue by muafakul** [GracesGames/2DTileMapLevelEditor#27]
just it

**Comment by GracesGames** [comment]
Please first try to find the answer on the [website](https://gracesgames.com/2DTileMapLevelEditor/).
There Level Editor script defines the Height, Width and amount of layers.

**Comment by muafakul** [comment]
i really dont know how to do it at all,,i mean the step by step

**Comment by GracesGames** [comment]
Then maybe its good to start with some [Unity tutorials](https://learn.unity.com/)

**Comment by muafakul** [comment]
just need the step by step about your project ,,,

Pada tanggal Kam, 15 Agu 2019 pukul 15.31 Graces Games <
notifications@github.com> menulis:
