### ISSUE TITLE
how to load the level using string , instead of nameoflevel.lvl

### ISSUE THREAD

**Issue by muafakul** [GracesGames/2DTileMapLevelEditor#30]
something like this 

public string content = "\t0-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,\n
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,\n
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,\n
-1,1,11,1,-1,-1,-1,-1,-1,-1,4,-1,-1,-1,-1,-1,\n
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,3,-1,-1,-1,\n
-1,2,-1,-1,-1,0,-1,-1,-1,-1,-1,3,-1,-1,-1,-1,\n
5,5,8,-1,-1,-1,-1,-1,-1,-1,3,-1,-1,2,-1,-1,\n
10,10,6,8,2,-1,-1,12,-1,-1,9,5,5,5,5,5,\n
10,10,10,6,5,5,5,5,5,5,7,10,10,10,10,10,\n
10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,\n";
		

```
		private void LoadLevelFromStringLayers (string content) {
			
			// Split our level on layers by the new tabs (\t)
			List<string> layers = new List<string> (content.Split ('\t'));
			foreach (string layer in layers) {
				if (layer.Trim () != "") {
					LoadLevelFromString (int.Parse (layer[0].ToString ()), layer.Substring (1));
				}
			}
		}
```

**Comment by muafakul** [comment]
i think if ido 	LoadLevelFromStringLayers ("\t0-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,\n
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,\n
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,\n
-1,1,11,1,-1,-1,-1,-1,-1,-1,4,-1,-1,-1,-1,-1,\n
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,3,-1,-1,-1,\n
-1,2,-1,-1,-1,0,-1,-1,-1,-1,-1,3,-1,-1,-1,-1,\n
5,5,8,-1,-1,-1,-1,-1,-1,-1,3,-1,-1,2,-1,-1,\n
10,10,6,8,2,-1,-1,12,-1,-1,9,5,5,5,5,5,\n
10,10,10,6,5,5,5,5,5,5,7,10,10,10,10,10,\n
10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,\n");  ,it should work ,but it does not work ,why

**Comment by muafakul** [comment]
it give me this error 

FormatException: Input string was not in the correct format
System.Int32.Parse (System.String s) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Int32.cs:629)

**Comment by GracesGames** [comment]
If you do it like that, you need to put the string on a single line to properly open and close it with `"`, you're editor should also give you an error.

**Comment by muafakul** [comment]
can you give me example how to do it ? ,,the correct way

**Comment by muafakul** [comment]
i am editor ?

**Comment by GracesGames** [comment]
> i am editor ?

No, I mean your code editor e.g. Visual Studio which I recommend for working with Unity. 
This will already indicate the compile error.

**Comment by GracesGames** [comment]
`LoadLevelFromStringLayers("\t0-1,-1,-1,-1,-1,-1,-1,-1,-1,\n- 1, -1, -1, -1...etcetera.`, 

putting the whole string on a single line as argument should work.
Also, please use the GitHub issues only for issues with the Level Editor and not issues with your personal projects. I would advise some tutorials since there is a knowledge gap.

**Comment by muafakul** [comment]
i did it but still doesnot work LoadLevelFromStringLayers ("\t0-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,\n-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,\n-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,\n-1,1,11,1,-1,-1,-1,-1,-1,-1,4,-1,-1,-1,-1,-1,\n-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,3,-1,-1,-1,\n-1,2,-1,-1,-1,0,-1,-1,-1,-1,-1,3,-1,-1,-1,-1,\n5,5,8,-1,-1,-1,-1,-1,-1,-1,3,-1,-1,2,-1,-1,\n10,10,6,8,2,-1,-1,12,-1,-1,9,5,5,5,5,5,\n10,10,10,6,5,5,5,5,5,5,7,10,10,10,10,10,\n10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,\n");

**Comment by muafakul** [comment]
it works now after i put invoke("failed" , 3f); 

void failed(){
LoadLevelFromStringLayers ("\t0-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,\n-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,\n-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,\n-1,1,11,1,-1,-1,-1,-1,-1,-1,4,-1,-1,-1,-1,-1,\n-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,3,-1,-1,-1,\n-1,2,-1,-1,-1,0,-1,-1,-1,-1,-1,3,-1,-1,-1,-1,\n5,5,8,-1,-1,-1,-1,-1,-1,-1,3,-1,-1,2,-1,-1,\n10,10,6,8,2,-1,-1,12,-1,-1,9,5,5,5,5,5,\n10,10,10,6,5,5,5,5,5,5,7,10,10,10,10,10,\n10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,\n");

}

**Comment by muafakul** [comment]
YESSS ,AHAHAHHA ,, IDID IT ,, SUCCEESS ,THANKS
