### ISSUE TITLE
wonderful editor,but how to load levels in a game?

### ISSUE THREAD

**Issue by igeeknerd** [GracesGames/2DTileMapLevelEditor#4]
I create levels and save them as .lvl files,but how to use these levels in my own games。

**Comment by igeeknerd** [comment]
Oh,I know.I have to copy hierarchy from Game Mode to Scene view......

**Comment by GracesGames** [comment]
As I personally use the level editor for one of my games, I have a way for that :)
I use the Level Editor methods LoadLevelFromStringLayers or LoadLevelUsingStringPath (latest version) to load the level and then ToggleLevelEditor(false) to disable the Level Editor. You could also remove the whole component of course. 
Hope that helps, else let me know and I'll try to make it work in another way.

**Comment by igeeknerd** [comment]
Thanks ,it works.

**Comment by GracesGames** [comment]
Great to hear, then I'll close this issue.
Let me know if you run into any other problems!
