### ISSUE TITLE
Can't include Level Editor in build - using UnityEditor namespace

### ISSUE THREAD

**Issue by stekeller** [GracesGames/2DTileMapLevelEditor#5]
Unfortunately the Editor can't be included in the build because the LevelEditor script is using the UnityEditor namespace.
![image](https://user-images.githubusercontent.com/6997722/28646044-fbc71468-725f-11e7-9c25-6a3db2f8dee9.png)

**Comment by GracesGames** [comment]
Thank you for creating an issue. I have confirmed it and will work on it starting tonight! An update on this issue will be posted when I have a working solution.

**Comment by GracesGames** [comment]
I have developed my own file browser to remove the dependency. 
It has been released on GitHub with version 1.2, which is currently under review for the Unity Store release. 

I hope that this solves your issue. If not or you encounter another one, please let me know.
