### ISSUE TITLE
How to setup?

### ISSUE THREAD

**Issue by binoculars88** [GracesGames/2DTileMapLevelEditor#8]
I'm not able to set it up right... I'm not seeing the game editor, only the grid.
I've followed the instructions on the wiki page. The only thing I didn't quite understand was "Add the prefab test tiles or your own files to the Tiles array". What do you mean by that?

Also, on play, I notice an error:
```
NullReferenceException: Object reference not set to an instance of an object
LevelEditor.SetupPrefabsButtons () (at Assets/2DTileMapLevelEditor/Scripts/LevelEditor.cs:384)
LevelEditor.SetupUI () (at Assets/2DTileMapLevelEditor/Scripts/LevelEditor.cs:224)
LevelEditor.Start () (at Assets/2DTileMapLevelEditor/Scripts/LevelEditor.cs:183)
```

Any chance you could help me with this issue?

**Comment by GracesGames** [comment]
The idea of the level editor is that the user can drag and drop their own tiles into the grid. 
These tiles should be [prefabs](https://docs.unity3d.com/Manual/Prefabs.html) created by the game developer (in this case probably you ;)). 

There is a Tiles array in the LevelEditor prefab, which could be empty on start:
![image](https://user-images.githubusercontent.com/27864009/29090687-a5e1e08e-7c80-11e7-827b-0472573fe3ea.png)

But that should be filled with tiles (prefabs) to build the level (e.g. the test tiles):
![image](https://user-images.githubusercontent.com/27864009/29090712-bb97ae0e-7c80-11e7-923e-916aa4a14134.png)

This should resolve the error, if not let me know.

**Comment by binoculars88** [comment]
Thanks for your reply! While it does work right now, I'm having trouble aligning it properly. I can't seem to find a good aspect. The select button is either invisible half visible. Any recommendations? Simply choosing 16:9 (example iPhone 5 Wide 16:9) doesn't make the editor visible.

**Comment by GracesGames** [comment]
Have you considered changing the width of the elements using the LevelEditor object? 

![image](https://user-images.githubusercontent.com/27864009/29091469-5e2d8d58-7c83-11e7-915d-ae4fd618bbfb.png)

I do not know the dimensions of your prefabs, but that might fix the problem :)

**Comment by binoculars88** [comment]
I'm using the included test prefabs to test it. Selecting a prefab and clicking the grid to place things works now, but I see no toolbar on the left...

**Comment by GracesGames** [comment]
Any errors in the log?
Are the demo scenes working correctly?
I use the editor myself for multiple project and have not yet encountered this 😅

**Comment by GracesGames** [comment]
Let me know if the error is resolved please, then I will close this issue :)

**Comment by binoculars88** [comment]
Tried it with a new project: it works!
Still can't figure out how it works though... I'm able to build a level, save it, etc., but the moment I "stop" the game, the level disappears. Or is this normal behavior? Is there a way to show the level in the scene?

**Comment by GracesGames** [comment]
That is indeed the normal behaviour. The levels should be saved as files which can then be used by your game in combination with the level editor. As described in #4:

I use the Level Editor methods LoadLevelUsingPath or LoadLevelFromStringLayers to load the level and then ToggleLevelEditor(false) to disable the Level Editor. You could also remove the whole component of course (destroy(game object) after loading.
Hope that helps, else let me know and I'll try to make it work in another way.
